name: lab_app
description: "A Flutter application for laboratory data processing."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  excel: ^4.0.0
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  csv: ^5.0.0
  fl_chart: ^0.65.0
  path: ^1.8.3
  charts_flutter: ^0.12.0  # Aggiunta questa riga mantenendo tutte le altre

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true